#############################################################################
# Makefile for building: asteroids
# Generated by qmake (3.0) (Qt 5.1.0) on: Wed Mar 26 10:43:19 2014
# Project:  asteroids.pro
# Template: app
# Command: /opt/qtsdk/5.1.0/gcc_64/bin/qmake -spec linux-clang CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile asteroids.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DLINUX -DLINUX -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -I/usr/local/include/SDL2 -D_REENTRANT -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/opt/qtsdk/5.1.0/gcc_64/mkspecs/linux-clang -I. -Iinclude -IC:\Program\ Files\Common\ Files\SDL2\include -I/opt/qtsdk/5.1.0/gcc_64/include -I/opt/qtsdk/5.1.0/gcc_64/include/QtOpenGL -I/opt/qtsdk/5.1.0/gcc_64/include/QtWidgets -I/opt/qtsdk/5.1.0/gcc_64/include/QtGui -I/opt/qtsdk/5.1.0/gcc_64/include/QtCore -I.
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Wl,-rpath,/opt/qtsdk/5.1.0/gcc_64 -Wl,-rpath,/opt/qtsdk/5.1.0/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lSDL2 -lGLEW -L/opt/qtsdk//5.1.0/gcc_64/lib -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk/5.1.0/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/GLFunctions.cpp \
		src/Vec4.cpp \
		src/Mat4.cpp \
		src/rigidbodies.cpp \
		src/rocket.cpp \
		src/asteroid.cpp \
		src/hud.cpp \
		src/world.cpp \
		src/camera.cpp \
		src/bullet.cpp \
		src/map.cpp \
		src/util.cpp 
OBJECTS       = obj/main.o \
		obj/GLFunctions.o \
		obj/Vec4.o \
		obj/Mat4.o \
		obj/rigidbodies.o \
		obj/rocket.o \
		obj/asteroid.o \
		obj/hud.o \
		obj/world.o \
		obj/camera.o \
		obj/bullet.o \
		obj/map.o \
		obj/util.o
DIST          = /opt/qtsdk/5.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/unix.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/linux.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/clang.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/qconfig.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/linux-clang/qmake.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/default_pre.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/default_post.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/declarative_debug.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/resources.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/moc.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/uic.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/yacc.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/lex.prf \
		asteroids.pro \
		asteroids.pro
QMAKE_TARGET  = asteroids
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = asteroids


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: asteroids.pro .qmake.cache /opt/qtsdk/5.1.0/gcc_64/mkspecs/linux-clang/qmake.conf /opt/qtsdk/5.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/unix.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/linux.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/clang.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/qconfig.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/linux-clang/qmake.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/default_pre.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/default_post.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/declarative_debug.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/resources.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/moc.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/uic.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/yacc.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/lex.prf \
		asteroids.pro \
		/opt/qtsdk/5.1.0/gcc_64/lib/libQt5OpenGL.prl \
		/opt/qtsdk/5.1.0/gcc_64/lib/libQt5Widgets.prl \
		/opt/qtsdk/5.1.0/gcc_64/lib/libQt5Gui.prl \
		/opt/qtsdk/5.1.0/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-clang CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile asteroids.pro
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/spec_pre.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/shell-unix.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/unix.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/linux.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/gcc-base.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/clang.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/qconfig.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt_functions.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt_config.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/linux-clang/qmake.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/spec_post.prf:
.qmake.cache:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/default_pre.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/resolve_config.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/default_post.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qml_debug.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/declarative_debug.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/warn_on.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/resources.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/moc.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/uic.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/thread.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/exceptions.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/yacc.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/lex.prf:
asteroids.pro:
/opt/qtsdk/5.1.0/gcc_64/lib/libQt5OpenGL.prl:
/opt/qtsdk/5.1.0/gcc_64/lib/libQt5Widgets.prl:
/opt/qtsdk/5.1.0/gcc_64/lib/libQt5Gui.prl:
/opt/qtsdk/5.1.0/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-clang CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile asteroids.pro

qmake_all: FORCE

dist: 
	@test -d obj/asteroids1.0.0 || mkdir -p obj/asteroids1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/asteroids1.0.0/ && $(COPY_FILE) --parents include/GLFunctions.h include/Vec4.h include/Mat4.h include/rigidbodies.h include/rocket.h include/asteroid.h include/hud.h include/World.h include/camera.h include/bullet.h include/map.h include/World.h include/util.h obj/asteroids1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/GLFunctions.cpp src/Vec4.cpp src/Mat4.cpp src/rigidbodies.cpp src/rocket.cpp src/asteroid.cpp src/hud.cpp src/world.cpp src/camera.cpp src/bullet.cpp src/map.cpp src/util.cpp obj/asteroids1.0.0/ && (cd `dirname obj/asteroids1.0.0` && $(TAR) asteroids1.0.0.tar asteroids1.0.0 && $(COMPRESS) asteroids1.0.0.tar) && $(MOVE) `dirname obj/asteroids1.0.0`/asteroids1.0.0.tar.gz . && $(DEL_FILE) -r obj/asteroids1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_qtwayland-client-header_make_all:
compiler_qtwayland-client-header_clean:
compiler_qtwayland-server-header_make_all:
compiler_qtwayland-server-header_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_qtwayland-client-code_make_all:
compiler_qtwayland-client-code_clean:
compiler_qtwayland-server-code_make_all:
compiler_qtwayland-server-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/main.o: src/main.cpp include/GLFunctions.h \
		include/Vec4.h \
		include/World.h \
		include/rocket.h \
		include/rigidbodies.h \
		include/Mat4.h \
		include/bullet.h \
		include/asteroid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/GLFunctions.o: src/GLFunctions.cpp include/GLFunctions.h \
		include/Vec4.h \
		include/Mat4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GLFunctions.o src/GLFunctions.cpp

obj/Vec4.o: src/Vec4.cpp include/Vec4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Vec4.o src/Vec4.cpp

obj/Mat4.o: src/Mat4.cpp include/Mat4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Mat4.o src/Mat4.cpp

obj/rigidbodies.o: src/rigidbodies.cpp include/rigidbodies.h \
		include/Vec4.h \
		include/GLFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/rigidbodies.o src/rigidbodies.cpp

obj/rocket.o: src/rocket.cpp include/rocket.h \
		include/rigidbodies.h \
		include/Vec4.h \
		include/Mat4.h \
		include/bullet.h \
		include/GLFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/rocket.o src/rocket.cpp

obj/asteroid.o: src/asteroid.cpp include/asteroid.h \
		include/rigidbodies.h \
		include/Vec4.h \
		include/GLFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/asteroid.o src/asteroid.cpp

obj/hud.o: src/hud.cpp include/hud.h \
		include/map.h \
		include/Vec4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/hud.o src/hud.cpp

obj/world.o: src/world.cpp include/World.h \
		include/rocket.h \
		include/rigidbodies.h \
		include/Vec4.h \
		include/Mat4.h \
		include/bullet.h \
		include/asteroid.h \
		include/GLFunctions.h \
		include/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/world.o src/world.cpp

obj/camera.o: src/camera.cpp include/camera.h \
		include/Vec4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/camera.o src/camera.cpp

obj/bullet.o: src/bullet.cpp include/bullet.h \
		include/rigidbodies.h \
		include/Vec4.h \
		include/GLFunctions.h \
		include/rocket.h \
		include/Mat4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/bullet.o src/bullet.cpp

obj/map.o: src/map.cpp include/map.h \
		include/Vec4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/map.o src/map.cpp

obj/util.o: src/util.cpp include/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/util.o src/util.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

